version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app
    networks:
      - proenv_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/:/opt/app/
    entrypoint: ["npm", "run", "start"]
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - proenv_network

networks:
  proenv_network:
    name: proenv_network
    driver: bridge