version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "443:443"
    volumes:
      - ./backend:/opt/app
      - /etc/pki/:/etc/pki
    networks:
      - proenv_network

networks:
  proenv_network:
    name: proenv_network
    driver: bridge