version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app
    networks:
      - proenv_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/:/opt/app/
    entrypoint: ["sh", "-c", "npm install react-scripts && npm run build"]
    depends_on:
      - backend
    networks:
      - proenv_network

  ingress:
    image: nginx:alpine
    container_name: ingress
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 8088:80
    depends_on:
      - frontend
    networks:
      - proenv_network

networks:
  proenv_network:
    name: proenv_network
    driver: bridge