version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    user: root
    volumes:
      - ./frontend/:/app/
    entrypoint: ["bash", "-lc", "npm install --savedev axios && npm run build"]
    depends_on:
      - backend

  ingress:
    image: nginx:alpine
    container_name: ingress
    restart: always
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:80
    depends_on:
      - backend
      - frontend
    