version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - backend
    