version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app
      - /etc/pki/:/etc/pki
    networks:
      - proenv_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/opt/app
    networks:
      - proenv_network

networks:
  proenv_network:
    name: proenv_network
    driver: bridge