name: Build Image and Push to GitHub Container Registry
run-name: BUILD - ${{ github.actor }} is trigger build/push with SHA:${{ github.sha }}

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      EC2_CONTAINER_NAME:
        required: true
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      EC2_KEY:
        required: true
      EC2_PORT:
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build only to test
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.EC2_CONTAINER_NAME }}:${{ github.sha }}

      - name: Get the version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: get_version
        run: |
          echo "IMAGE_VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')" >> $GITHUB_OUTPUT

      - name: Get public ip address of ec2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: get_public_ip
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            export PUBLIC_IP_ADDRESS=$(curl http://checkip.amazonaws.com)
            echo "::set-output name=public_ip_address::$PUBLIC_IP_ADDRESS"

      - name: Test public ip address
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo ${{ steps.get_public_ip.outputs.PUBLIC_IP_ADDRESS }}

      - name: Build and push image to GCR
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.EC2_CONTAINER_NAME }}:${{ steps.get_version.outputs.IMAGE_VERSION }}
          build-args: |
            PUBLIC_IP_ADDRESS=${{ steps.get_public_ip.outputs.PUBLIC_IP_ADDRESS }}
