name: Build Image and Push to GitHub Container Registry
run-name: BUILD - ${{ github.actor }} is trigger build/push with SHA:${{ github.sha }}

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      AWS_ARN:
        required: true
      AWS_REGION:
        required: true
      EC2_INSTANCE_ID:
        required: true
      EC2_CONTAINER_NAME:
        required: true
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      EC2_KEY:
        required: true
      EC2_PORT:
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build only to test
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.EC2_CONTAINER_NAME }}:${{ github.sha }}

      - name: Get the version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: get_version
        run: |
          echo "IMAGE_VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials from Test account
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          role-session-name: ${{ github.actor }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get public IP address using AWS CLI
        id: get_public_ip
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          IP_ADDRESS=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo "public_ip_address=$IP_ADDRESS" >> $GITHUB_OUTPUT

      - name: Test public ip address
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo ${{ steps.get_public_ip.outputs.public_ip_address }}

      - name: Build and push image to GCR
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.EC2_CONTAINER_NAME }}:${{ steps.get_version.outputs.IMAGE_VERSION }}
          build-args: |
            PUBLIC_IP_ADDRESS=${{ steps.get_public_ip.outputs.public_ip_address }}
